### ISSUE TITLE
Source/Api/API_Value.hx missing

### ISSUE THREAD

**Issue by anissen** [Tomobodo/Nodax#1]
In `Macros.hx`, `classesToParse` contains `API_Math` and `API_Value` but `Source/API/API_Value.hx` is missing from the repository leading to the following compile error:

```
$ openfl test flash
Source/macros/Macros.hx:25: characters 22-31 : Unknown identifier : API_Value
Export/flash/haxe/ApplicationMain.hx:229: characters 12-17 : Build failure
```

**Comment by Tomobodo** [comment]
oops, seems like I forgot to add the file. Thanks you for the report, i uploaded it.
