### ISSUE TITLE
Continuation of this project!

### ISSUE THREAD

**Issue by darmie** [Tomobodo/Nodax#2]
Hi @TBaudon, this is a lovely project and I would love to use it for educational purpose (for kids). I am from a Javascript background and my Haxe knowledge is limited. Can you please continue on this project? 

Thank you!

**Comment by Tomobodo** [comment]
Hello, thank you for your interest in this project.
I did not forget this project :). 
I'm working on another project wich will probably use what I've done here.

As you can see we can't do much but moving a yellow circle so it's not really usefull. 
I'm currently working on creating game objects and manipulating them, and this project will integrate as a scripting system. 

The fact that you want to use it for educatioinal puprose reminds me that I should keep the ui simple and pleasant. 

Have a nice day!

**Comment by darmie** [comment]
Thank you! :)

**Comment by darmie** [comment]
@Tbaudon are you the tschery  guy on Twitter. He seems to be working on something similar to Nodax. And I can't wait to see an improved version of Nodax that can build actual games :)

**Comment by darmie** [comment]
Hi @TBaudon  I am here again :) , Have you seen [NoFlo](http://noflojs.org)? It's opensource, do you think it would be possible to get a working implementation of Noflo port to Haxe? I attempted it and realize i would need to use Reflections a lot to dynamically add or remove ports.. 

I'd be willing to work with you on improving Nodax if you are still interested.
